# Logistic Regression

## Importing the libraries

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Importing the dataset

In [10]:
dataset = pd.read_csv("Social_Network_Ads.csv")
x = dataset.iloc[:,:2].values
y = dataset.iloc[:,2:].values

In [8]:
print(x)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [11]:
print(y)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]


## Splitting the dataset into the Training set and Test set

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.3, random_state = 1)

## Feature Scaling

In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [55]:
print(x_train)

[[-9.79100420e-01 -1.11059025e+00]
 [-2.03575335e-01  5.66967998e-02]
 [ 1.15359356e+00 -1.19813678e+00]
 [-2.03575335e-01  6.40340327e-01]
 [-9.69406357e-03  1.73425505e-01]
 [-4.94397242e-01  1.39907691e+00]
 [-1.06634699e-01  1.73425505e-01]
 [-1.65768487e+00  4.94429445e-01]
 [ 8.72465721e-02 -5.56128904e-01]
 [ 1.15359356e+00 -9.64679373e-01]
 [ 2.81127843e-01 -1.18396258e-01]
 [-9.69406357e-03  2.31789858e-01]
 [ 2.21994056e+00 -6.72857609e-01]
 [ 1.05665293e+00  2.01190262e+00]
 [ 2.81127843e-01  5.66967998e-02]
 [-1.06634699e-01 -1.76760611e-01]
 [-1.07604106e+00  3.48518563e-01]
 [-3.97456606e-01 -1.11059025e+00]
 [ 3.78068479e-01 -5.26946727e-01]
 [ 8.62771657e-01  1.44243329e-01]
 [-1.85156614e+00  3.77700740e-01]
 [-9.69406357e-03 -1.05222590e+00]
 [-2.03575335e-01 -4.68582375e-01]
 [-8.82159785e-01 -2.93489316e-01]
 [-9.69406357e-03  5.66967998e-02]
 [-1.85156614e+00 -7.31221962e-01]
 [ 8.72465721e-02 -2.35124964e-01]
 [-2.03575335e-01 -1.18396258e-01]
 [-5.91337878e-01 -8

In [56]:
print(x_test)

[[-0.27545144 -1.14462515]
 [ 0.00466867 -0.30873284]
 [-0.27545144  1.39290506]
 [ 0.00466867  1.51231825]
 [-1.20918512  1.39290506]
 [-0.0887047  -0.18931966]
 [-1.76942532 -1.05506526]
 [ 0.93840235  0.52715946]
 [-0.74231828 -1.5924246 ]
 [ 0.84502898  2.07953089]
 [-0.46219817  0.01965342]
 [ 0.00466867  0.04950672]
 [-0.3688248   0.01965342]
 [ 0.84502898  1.78099792]
 [ 1.31189582  0.31818639]
 [ 1.59201592  1.84070451]
 [ 1.9655094   0.34803968]
 [-1.11581175 -0.39829273]
 [-1.02243838  0.46745287]
 [ 1.9655094   0.91525232]
 [ 0.09804204  0.10921331]
 [ 1.03177572  0.49730617]
 [ 0.47153551  2.01982429]
 [ 0.75165561 -0.84609218]
 [ 0.56490888 -1.35359822]
 [-1.20918512 -1.68198449]
 [ 1.77876266 -0.72667899]
 [ 0.93840235  0.07936001]
 [ 1.31189582 -1.11477185]
 [ 1.21852245  1.27349188]
 [ 0.00466867 -0.87594548]
 [-1.86279869  0.13906661]
 [-1.95617206  0.43759957]
 [ 1.68538929  0.07936001]
 [-1.11581175  0.37789298]
 [-0.83569164  0.25847979]
 [-1.58267859 -1.5924246 ]
 

## Training the Logistic Regression model on the Training set

In [57]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

## Predicting a new result

In [58]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


## Predicting the Test set results

In [59]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]]


## Making the Confusion Matrix

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("confusion Matrix:\n",cm)
print("Accuracy Score:",accuracy_score(y_test, y_pred))

confusion Matrix:
 [[65  7]
 [18 30]]
Accuracy Score: 0.7916666666666666
