<a href="https://colab.research.google.com/github/Udayr777/Machine-Learning/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
# importing Libraries
import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score


In [5]:
# load the dataset
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [6]:
train.head()

x          y
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [8]:
test.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [10]:
# checking the shape of the dataset
print(f'Shape of the training dataset is {train.shape}')
print(f'Shape of the testing dataset is {test.shape}')

Shape of the training dataset is (700, 2)
Shape of the testing dataset is (300, 2)


In [12]:
# total missing values for training dataset
missing_values_train = train.isnull().sum()
missing_values_train

x    0
y    1
dtype: int64

In [13]:
# total missing values for training dataset
missing_values_test = test.isnull().sum()
missing_values_test

x    0
y    0
dtype: int64

In [15]:
# missing values removal
train = train.dropna()
train.head()

x          y
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [16]:
# checking total missing values for training dataset
missing_values_train = train.isnull().sum()
missing_values_train

x    0
y    0
dtype: int64

In [17]:
train.shape

(699, 2)

In [19]:
# set training tragets

X_train = train['x']
y_train = train['y']

# set testing tragets

X_test = test['x']
y_test = test['y']

In [20]:
X_train.head()
y_train.head()

0    21.549452
1    47.464463
2    17.218656
3    36.586398
4    87.288984
Name: y, dtype: float64

In [21]:
X_train = X_train.values.reshape(-1,1)
X_test = X_test.values.reshape(-1, 1)

In [27]:
X_train
X_test

array([[ 77],
       [ 21],
       [ 22],
       [ 20],
       [ 36],
       [ 15],
       [ 62],
       [ 95],
       [ 20],
       [  5],
       [  4],
       [ 19],
       [ 96],
       [ 62],
       [ 36],
       [ 15],
       [ 65],
       [ 14],
       [ 87],
       [ 69],
       [ 89],
       [ 51],
       [ 89],
       [ 27],
       [ 97],
       [ 58],
       [ 79],
       [ 21],
       [ 93],
       [ 27],
       [ 99],
       [ 31],
       [ 33],
       [ 80],
       [ 28],
       [ 47],
       [ 53],
       [ 69],
       [ 28],
       [ 33],
       [ 91],
       [ 71],
       [ 50],
       [ 76],
       [  4],
       [ 37],
       [ 70],
       [ 68],
       [ 40],
       [ 35],
       [ 94],
       [ 88],
       [ 52],
       [ 31],
       [ 59],
       [  0],
       [ 39],
       [ 64],
       [ 69],
       [ 57],
       [ 13],
       [ 72],
       [ 76],
       [ 61],
       [ 82],
       [ 18],
       [ 41],
       [ 50],
       [ 55],
       [ 13],
       [ 46],
      

In [41]:
sc = StandardScaler()
# sc.fit(X_train)
sc.fit(X_test)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [42]:
X_train[:5]

array([[-0.94658305],
       [-0.03291546],
       [-1.2628526 ],
       [-0.45460819],
       [ 1.2673038 ]])

In [43]:
X_test[:5]

array([[ 0.91589319],
       [-1.05200623],
       [-1.01686517],
       [-1.08714729],
       [-0.52489032]])

In [44]:
X_train.min(), X_train.max()

(-1.7899685147895597, 1.7241375936906962)

In [47]:
px.scatter(x=train['x'], y=train['y'], template='gridon')

In [48]:
px.scatter(x=test['x'], y=test['y'], template='gridon')

In [50]:
# Model selection
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [55]:
# Evaluation Mean Square Error
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
mse

9.43292219203931

In [59]:
# Evaluation Mean Absoulte Error
mae = mean_absolute_error(y_test, y_pred)
mae

2.415771850041258

In [60]:
# root square error
r2 = r2_score(y_test, y_pred)
r2

0.9888014444327563